apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: aothrones.azurecr.io/api
    context: api
  - image: aothrones.azurecr.io/postgis
    context: db
  - image: aothrones.azurecr.io/frontend
    context: frontend
    sync: #sync app assets without forcing a docker rebuild
      manual:
        - src: 'app/**'
          dest: .
        - src: 'public/index.html'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
