apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 5000
    name: api
  selector:
    app: api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-redis
        image: redis:5-alpine
        command: ['sh', '-c',
          'until redis-cli -h redis ping;
          do echo waiting for redis; sleep 1; done;']
      - name: wait-for-postgres
        image: postgres:12-alpine
        command: ['sh', '-c', 
          'until pg_isready -h postgres -U patrick -d atlas_of_thrones -p 5432; 
          do echo waiting for postgres; sleep 1; done;']
      containers:
      - name: api
        image: aothrones.azurecr.io/api
        ports:
        - containerPort: 5000
          name: api
        env:
        - name: DATABASE_URL
          value: "postgres://patrick:@postgres:5432/atlas_of_thrones"
        - name: REDIS_HOST
          value: redis
        livenessProbe:
          httpGet:
            path: /hello
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
